package ua.tqs.hw1;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class Api {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","./chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://localhost:8080/");
    driver.manage().window().maximize();
    driver.findElement(By.id("myloc")).click();
    driver.findElement(By.id("myloc")).sendKeys("oPorto");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".today")).click();
    assertThat(driver.findElement(By.cssSelector(".today span")).getText(), is("Latitude, Longitude: 41.1475, -8.658889"));
    assertThat(driver.findElement(By.cssSelector(".location")).getText(), is("oPorto"));
  }
}
