package ua.tqs.hw1;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

public class Sel_CityNotExists {
  private WebDriver driver;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","./chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() {
    driver.get("http://localhost:8080/");
    driver.manage().window().maximize();
    driver.findElement(By.id("myloc")).click();
    driver.findElement(By.id("myloc")).sendKeys("asd");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.cssSelector(".num")).getText(), is("AQI: 1 Search a City"));
    assertThat(driver.findElement(By.cssSelector("span")).getText(), is("Latitude, Longitude: null, null"));
  }
}
